export type ChatbotSlide = {
  eyebrow: string
  title: string
  subtitle?: string
  layout: "cover" | "overview" | "keywords" | "timeline" | "cards" | "flow" | "conversation" | "dashboard" | "links" | "checklist" | "happiest" | "challenge" | "closing" | "thankYou" | "qa"
  lead?: string
  items?: string[]
  cards?: { title: string; body: string; tag?: string; icon?: string }[]
  closingStatement?: string
  flow?: string[]
  links?: { label: string; href: string; qr: string }[]
  presenter?: { name: string; role: string; period: string }
  notes: string
}

export const CHATBOT_SLIDES: ChatbotSlide[] = [
  { eyebrow: "LOCUS-T × DigitalBee", title: "Final\nPresentation", subtitle: "AI Chatbots, CRM Dashboards & Business Automation", layout: "cover", presenter: { name: "Nur Iman Binti Noor Azizi", role: "Developer Intern", period: "20th April 2026 - 7 August 2026" }, notes: "Good morning everyone. My name is Nur Iman Binti Noor Azizi. During my internship at LOCUS-T and DigitalBee, I explored AI chatbot development, CRM dashboards and business automation. Today, I will share how this journey developed from simple prompt experiments into systems that could support real business workflows." },
  { eyebrow: "INTERNSHIP FINAL PRESENTATION", title: "Presentation\nOverview", layout: "overview", notes: "This presentation begins with why I chose DigitalBee, followed by my chatbot journey and project showcase. I will then share the main challenges I faced, the solutions I applied, and conclude with my reflection and future direction." },
  { eyebrow: "01 / Internship choice", title: "Why\nDigitalBee?", layout: "keywords", lead: "I wanted to see how AI works inside real business systems.", closingStatement: "I wanted to build and experiment—not only follow instructions.", cards: [{ title: "AI Beyond ChatGPT", body: "Learn how AI works outside the ChatGPT interface." }, { title: "AI in Real-Time Systems", body: "See how AI receives, processes and responds to messages in live workflows." }, { title: "Freedom to Explore", body: "Research, test and improve tools and workflows independently." }], notes: "I chose DigitalBee because I wanted to explore how AI could support actual business operations. I did not only want to use ChatGPT to generate text. I wanted to understand how an AI assistant could connect with a website, customer information, WhatsApp and a dashboard." },
  { eyebrow: "02 / Journey", title: "My chatbot\njourney", layout: "timeline", subtitle: "Preview trailer · 30–45 seconds", flow: ["MyGPT Experimentation", "Content Assistant", "Custom OpenAI Chatbot", "CRM & Human Handoff", "Reusable Business System"], notes: "My chatbot journey can be divided into five stages. I began with MyGPT, then developed a content assistant, moved into a custom OpenAI chatbot, explored CRM dashboards and human handoff, and finally tested a reusable architecture for several businesses." },
  { eyebrow: "03 / MyGPT & AllLove", title: "Teaching AI how\nto communicate", layout: "cards", subtitle: "AllLove · Short-form Product Script Assistant", cards: [{ title: "PURPOSE", body: "20–60 second product scripts" }, { title: "TONE", body: "Natural, warm and professional" }, { title: "BOUNDARIES", body: "No robotic or overly sales-focused writing" }, { title: "TAKEAWAY", body: "Role + tone + structure + examples" }], notes: "My first main chatbot experiment was AllLove, a MyGPT assistant for short-form product scripts. I learned that a good chatbot needs a role, tone, boundaries, structure and examples—not just one simple prompt." },
  { eyebrow: "04 / Custom OpenAI chatbot", title: "Moving beyond\nChatGPT", layout: "flow", lead: "A business chatbot needs to work inside the customer journey, not only inside ChatGPT.", flow: ["Website User", "Chat Interface", "OpenAI Assistant", "Business Instructions", "Generated Response"], notes: "MyGPT helped me understand prompt behaviour, but a business chatbot must operate outside ChatGPT. The website sends the customer message to the OpenAI assistant with business instructions, then returns a suitable response through a custom interface." },
  { eyebrow: "05 / Architecture", title: "One system.\nMultiple businesses.", layout: "flow", lead: "The architecture stays the same. Business knowledge and conversation flow change.", flow: ["Website or WhatsApp Entry", "Tracked Reference ID", "Correct Chatbot Flow", "AI Response", "Lead Stored in CRM", "Human Follow-up"], notes: "Instead of building a separate application for every business, I explored a reusable chatbot architecture. The entry point identifies the business, the system loads the correct instructions, AI handles the early conversation, and a staff member can continue when required." },
  { eyebrow: "06 / Business flows", title: "Four businesses.\nFour conversation flows.", layout: "cards", cards: [{ title: "SiteTarik", tag: "Real website", body: "Website goals, package guidance and next steps" }, { title: "Ornis", tag: "Real website", body: "Product enquiries and basic customer service" }, { title: "Boon Chye", tag: "Demo", body: "Home-repair questions and service details" }, { title: "Rumah Mampu", tag: "Demo", body: "Housing interest and buyer information" }], notes: "I tested one reusable structure with four business scenarios. Although the industries were different, every chatbot answered common questions, understood customer needs, collected information and prepared the conversation for human follow-up." },
  { eyebrow: "07 / SiteTarik", title: "From question to\npackage recommendation", layout: "conversation", lead: "The chatbot asks for the existing website and customer goal before recommending a suitable option.", cards: [{ title: "CORE REBORN", tag: "RM100 / year", body: "Website refresh, basic SEO and hosting" }, { title: "SEO ENHANCEMENT", tag: "RM220 total", body: "Core Reborn + 12 SEO-friendly blog pages" }], notes: "SiteTarik was one of the strongest examples of applying AI to a clear business process. The chatbot collects the customer website and goal, explains packages and recommends the relevant option. It must not promise custom redesigns, guaranteed rankings or services outside the package." },
  { eyebrow: "08 / CRM dashboard", title: "AI starts the conversation.\nHumans complete it.", layout: "dashboard", cards: [{ title: "CONVERSATION", body: "Customer message, AI reply and history" }, { title: "LEAD INFORMATION", body: "Name, WhatsApp, website, goal and reference ID" }, { title: "HUMAN ACTION", body: "Review, reply, add notes and follow up" }], notes: "A chatbot should not replace human communication. I explored Chatwoot as a conversation dashboard and human-support layer. Staff can review prior messages, understand needs and continue the conversation without asking the customer to repeat everything." },
  { eyebrow: "09 / R&D interfaces", title: "Testing chatbots\ninside real websites", layout: "links", lead: "R&D websites helped me test chatbot placement, responsive layouts and dashboard concepts.", links: [{ label: "Whatever Works Coffee", href: "https://whatever-works-coffee.vercel.app/", qr: "whatever-works.png" }, { label: "Coffee Admin Prototype", href: "https://whatever-works-coffee.vercel.app/admin", qr: "coffee-admin.png" }, { label: "SiteTarik Chatbot V2", href: "https://sitetarik-chatbot-v2.easondev.workers.dev/", qr: "sitetarik-v2.png" }, { label: "SiteTarik Dashboard", href: "https://sitetarik-chatbot-v2.easondev.workers.dev/dashboard", qr: "sitetarik-dashboard.png" }], notes: "I used Shuffle and web-development tools to prototype how chatbots could fit inside complete website interfaces. Whatever Works Coffee was an R&D website and SiteTarik Chatbot V2 added a custom interface, dashboard access and lead monitoring." },
  { eyebrow: "10 / Live demonstration", title: "Let’s test\nthe system", layout: "checklist", items: ["Open SiteTarik Chatbot V2", "Enter a realistic customer enquiry", "Show follow-up questions", "Show package recommendation", "Open dashboard and review the lead"], lead: "Backup: screen recording if the connection or AI response is unavailable.", notes: "In this demonstration, the chatbot identifies the customer need, asks relevant questions and guides the user toward a suitable option. At the same time, the business can review the captured information through the dashboard." },
  { eyebrow: "11 / Project milestone", title: "My Most\nExciting Moment", layout: "happiest", lead: "When the AI finally spoke the way I wanted.", subtitle: "After repeated prompt testing and refinement, the chatbot responded with the intended tone, structure and business logic.", notes: "My most exciting moment was when the prompt finally made the AI communicate the way I wanted.\n\nAt the beginning, some responses were too general, too long or did not follow the intended conversation flow. I repeatedly tested the chatbot, adjusted the instructions and added clearer rules, restrictions and examples.\n\nEventually, the chatbot responded with the correct tone, asked relevant follow-up questions and followed the business requirements more consistently. The conversation also appeared correctly in the Chatwoot dashboard.\n\nI did not face a major problem with the tools I was using. The most satisfying part was learning how to control the AI’s behaviour through better prompt design.\n\nThis moment helped me understand that prompt engineering is not only about writing one instruction. It involves testing, observing the response, identifying weaknesses and improving the instructions until the chatbot behaves as intended." },
  { eyebrow: "12 / Biggest challenge", title: "My Biggest\nChallenge", layout: "challenge", lead: "How do I make AI flexible without making it uncontrolled?", subtitle: "A chatbot can generate an answer, but a business system needs the correct answer.", notes: "My biggest challenge was making the chatbot system reusable for different businesses without making the AI too general or uncontrolled.\n\nEach business had different information, services and customer goals. For example, the SiteTarik chatbot needed to understand website-related enquiries and recommend the correct package. Other chatbots had completely different purposes, such as product enquiries, home-repair services or affordable housing leads.\n\nWithout clear business instructions, the AI could provide information that was not supported, recommend the wrong service, produce an answer that was too long or promise something that the business could not provide.\n\nThe technical workflow was also challenging. I needed to understand how the customer’s entry source, reference ID, business-specific chatbot instructions, lead information and CRM dashboard should remain connected.\n\nThis experience taught me that generating an AI response is not the most difficult part. The real challenge is ensuring that the response is accurate, relevant, controlled and useful for the business." },
  { eyebrow: "13 / Solution", title: "Separate. Restrict.\nTrack. Test. Escalate.", layout: "checklist", items: ["Separate instructions for every business", "Restrict unsupported promises", "Track lead and reference information", "Test incomplete and repeated enquiries", "Escalate complex cases to a human"], notes: "I overcame this by separating instructions for every business, defining restrictions, tracking customer data and testing many message types. A good chatbot does not need to answer everything; it must know when human support is required." },
  { eyebrow: "14 / Reflection", title: "What makes me\ndifferent from AI?", layout: "closing", subtitle: "Reflection & Future", lead: "Learn how to verify AI, connect it and turn it into a working system.", cards: [{ title: "AI", body: "Generates replies quickly" }, { title: "ME", body: "Checks if they are correct, useful and responsible" }, { title: "AI", body: "Follows instructions" }, { title: "ME", body: "Understands the business objective behind them" }], notes: "Before this internship, I viewed a chatbot mainly as a tool that answers questions. Now I understand that it is one part of a larger system involving business rules, customer experience, data, dashboards and human follow-up. AI helped me work faster, but it could not replace my responsibility to understand the problem, check the output and make decisions." },
  { eyebrow: "15 / Closing", title: "Thank\nYou", layout: "thankYou", lead: "Thank you for the guidance, trust and opportunity to explore.", subtitle: "This internship started with curiosity and ended with a clearer direction for my future.", notes: "Before I move to the question-and-answer session, I would like to thank LOCUS-T, DigitalBee, my supervisors, the team and my fellow interns for their guidance and support.\n\nThis internship gave me the opportunity to explore artificial intelligence beyond ChatGPT, test my own ideas and understand how chatbots, websites, dashboards and business workflows can work together.\n\nAnd after preparing all of these slides, I am also happy to say that the presentation is finally done. Thank you for listening." },
  { eyebrow: "16 / Q&A", title: "Questions\n& Answers", layout: "qa", lead: "I’m ready for your questions.", subtitle: "ChatGPT later. Ask me first.", notes: "Thank you again for your attention. I am now ready for your questions.\n\nThe meme says to search in ChatGPT, but today you can ask me first." },
]

export const PRESENTER_NOTES = CHATBOT_SLIDES.map((slide, index) => ({ slide: index + 1, title: slide.title.replace("\n", " "), script: slide.notes }))
