export type ChatbotSlide = {
  eyebrow: string
  title: string
  subtitle?: string
  layout: "cover" | "overview" | "keywords" | "timeline" | "preview" | "showcase" | "cards" | "flow" | "breakthrough" | "openai" | "conversation" | "dashboard" | "links" | "checklist" | "happiest" | "challengeEmotion" | "challenge" | "closing" | "finalQna"
  lead?: string
  items?: string[]
  cards?: { title: string; body: string; tag?: string; icon?: string }[]
  closingStatement?: string
  flow?: string[]
  links?: { label: string; href: string; qr: string; actionLabel?: string }[]
  presenter?: { name: string; role: string; period: string }
  notes: string
}

export const CHATBOT_SLIDES: ChatbotSlide[] = [
  { eyebrow: "LOCUS-T × Digital Bee", title: "Final\nPresentation", subtitle: "AI Chatbots, CRM Dashboards & Business Automation", layout: "cover", presenter: { name: "Nur Iman Binti Noor Azizi", role: "Developer Intern", period: "20th April 2026 - 7 August 2026" }, notes: "Good morning everyone. My name is Nur Iman Binti Noor Azizi. During my internship at LOCUS-T and Digital Bee, I explored AI chatbot development, CRM dashboards and business automation. Today, I will share how this journey developed from simple prompt experiments into systems that could support real business workflows." },
  { eyebrow: "INTERNSHIP FINAL PRESENTATION", title: "Presentation\nOverview", layout: "overview", notes: "This presentation begins with why I chose Digital Bee, followed by my chatbot journey and project showcase. I will then share the main challenges I faced, the solutions I applied, and conclude with my reflection and future direction." },
  { eyebrow: "01 / Internship choice", title: "Why\nDigitalBee?", layout: "keywords", lead: "I wanted to see how AI works inside real business systems.", closingStatement: "I wanted to build and experiment—not only follow instructions.", cards: [{ title: "AI Beyond ChatGPT", body: "Learn how AI is configured and tested through the OpenAI Platform." }, { title: "AI in Business Flows", body: "See how prompts, business knowledge, WhatsApp and tracked reference IDs work together." }, { title: "Freedom to Explore", body: "Research, test and improve tools and workflows independently." }], notes: "I chose Digital Bee because I wanted to explore how AI could support actual business operations. I did not only want to use ChatGPT to generate text. I wanted to understand how an AI assistant could connect with business knowledge, WhatsApp and tracked reference IDs." },
  { eyebrow: "02 / Journey", title: "Project\nOverview", layout: "timeline", subtitle: "From prompt experiments to deployed business workflows.", flow: ["Prompt Experimentation", "Content Assistant", "OpenAI Platform", "WhatsApp & CRM Flow", "Deployment & Reusable System"], notes: "This project began with prompt experimentation in MyGPT, followed by the AllLove content assistant. The main chatbot work was built in the OpenAI Platform, where I configured business knowledge, instructions and response behaviour. I then tested WhatsApp reference-ID routing and completed Chatwoot handoff during my internship. Finally, I deployed reusable flows for SiteTarik, Ornis, Boon Chye and Rumah Mampu for online testing." },
  { eyebrow: "03 / Project preview", title: "Project\nPreview", layout: "preview", subtitle: "35–45 second project montage", lead: "A quick look at how prompt experiments became reusable business workflows.", notes: "This short project preview introduces the journey from early prompt experimentation to deployed business workflows. I will briefly show the OpenAI configuration, WhatsApp reference-ID routing and the reusable business flows before continuing with the detailed slides." },
  { eyebrow: "Project Showcase & Live Demo", title: "OpenAI Business\nChatbot", layout: "showcase", subtitle: "From prompt development to WhatsApp routing.", notes: "This showcase focuses on the OpenAI business chatbot. The project trailer shows prompt configuration, response testing and WhatsApp routing. The public WhatsApp Demo Hub does not host a chatbot conversation directly; it lets a user select a business and then routes them into WhatsApp with the correct tracked reference ID." },
  { eyebrow: "My Most Exciting Moment", title: "It finally spoke\nthe way I imagined.", layout: "breakthrough", lead: "After repeated testing and prompt refinement, the chatbot finally followed my intended tone, business knowledge and conversation flow.", subtitle: "It proved that I could shape AI behaviour through careful testing and improvement.", flow: ["Write", "Test", "Notice", "Refine", "It Worked ✦"], notes: "My happiest moment was when my prompt finally worked exactly the way I wanted. After repeated testing and refinement, the chatbot followed the intended tone, business knowledge and conversation flow. This showed me that prompt writing is not only giving instructions; it is a process of testing, observing, improving and shaping AI behaviour." },
  { eyebrow: "05 / Architecture", title: "One system.\nMultiple businesses.", layout: "flow", lead: "The demo hub identifies the selected business using a tracked reference ID, while each business uses its own chatbot instructions and conversation flow.", subtitle: "Separate flows were prepared for SiteTarik, Ornis, Boon Chye and Rumah Mampu.", flow: ["WhatsApp Demo Hub", "Select Business Flow", "Open WhatsApp", "Tracked Reference ID", "Correct Business Instructions", "AI Response", "Human Follow-up"], notes: "The demo hub contains multiple business options. When a user presses Open WhatsApp, WhatsApp opens with a tracked reference ID. That reference ID indicates the correct business flow, while the chatbot instructions remain separate for each business. The reusable system covered SiteTarik, Ornis, Boon Chye and Rumah Mampu." },
  { eyebrow: "My Biggest Challenge", title: "What if it wasn’t\ngood enough?", layout: "challengeEmotion", lead: "My biggest challenge was not knowing whether the chatbot would meet the expected quality and business requirements.", closingStatement: "I felt nervous because I was responsible for deciding when the output was ready.", cards: [{ title: "Unclear Benchmark", body: "There was no single correct answer to compare against." }, { title: "Inconsistent AI", body: "A small prompt change could produce a very different response." }, { title: "Personal Pressure", body: "I wanted the final result to be useful, accurate and worth presenting." }], notes: "My biggest challenge was not knowing whether the chatbot would meet the expected quality and business requirements. There was no single correct answer to compare against, and even a small prompt change could produce a different response. I felt nervous because I was responsible for deciding when the output was ready. The next section explains how I tested different questions, refined instructions, checked business requirements and asked for feedback until the response became more consistent." },
  { eyebrow: "07 / SiteTarik WhatsApp flow", title: "From question to\npackage recommendation", layout: "conversation", subtitle: "DEMO HUB → WHATSAPP + REF ID → PACKAGE GUIDANCE", lead: "The user enters through the demo hub, opens WhatsApp with a tracked reference ID and continues through the SiteTarik enquiry flow.", cards: [{ title: "CORE REBORN", tag: "RM100 / year", body: "Website refresh, basic SEO and hosting" }, { title: "SEO ENHANCEMENT", tag: "RM220 total", body: "Core Reborn + 12 SEO-friendly blog pages" }], notes: "For SiteTarik, the user enters through the demo hub, opens WhatsApp with a tracked reference ID and continues through the SiteTarik enquiry flow. The conversation asks for the current website and main goal before guiding the customer toward a suitable package." },
  { eyebrow: "08 / Previous CRM integration", title: "AI starts the conversation.\nHumans can continue it.", layout: "dashboard", subtitle: "INTEGRATION COMPLETED DURING INTERNSHIP", closingStatement: "Live Chatwoot access is no longer used for this presentation.", cards: [{ title: "CONVERSATION HISTORY", body: "Customer messages and AI responses were previously visible in one inbox." }, { title: "LEAD INFORMATION", body: "Business flow, customer information and tracked reference ID." }, { title: "HUMAN FOLLOW-UP", body: "Staff could review the conversation and continue when required." }], notes: "Chatwoot was part of the completed internship integration. Customer messages and AI responses were previously visible in one inbox, together with lead information and the tracked reference ID. Live Chatwoot access is no longer used for this presentation, so this remains a previous integration rather than the live demonstration." },
  { eyebrow: "09 / R&D interfaces", title: "Testing chatbots\ninside real websites", layout: "links", lead: "The R&D interfaces helped me test website layouts, WhatsApp entry points, tracked reference IDs and dashboard concepts.", links: [{ label: "Whatever Works Coffee", href: "https://whatever-works-coffee.vercel.app/", qr: "whatever-works.png" }, { label: "Coffee Admin Prototype", href: "https://whatever-works-coffee.vercel.app/admin", qr: "coffee-admin.png" }, { label: "WhatsApp Demo Hub", href: "https://sitetarik-chatbot-v2.easondev.workers.dev/", qr: "sitetarik-v2.png", actionLabel: "Open WhatsApp demo hub" }], notes: "The R&D interfaces helped me test website layouts, WhatsApp entry points, tracked reference IDs and dashboard concepts. The WhatsApp Demo Hub lets the user select a business flow and then opens WhatsApp with the correct tracked reference ID." },
  { eyebrow: "10 / OpenAI live demonstration", title: "Let’s test\nWA-Ornis", layout: "checklist", items: ["Open the WA-Ornis prompt in the OpenAI Platform", "Briefly show the business knowledge and chatbot instructions", "Enter a realistic customer question", "Review the response and follow-up question", "Explain how the prompt was refined for accuracy and brand alignment"], lead: "Backup: use the OpenAI Platform screenshot if live access or generation is unavailable.", closingStatement: "The WhatsApp Demo Hub can also be shown briefly to demonstrate how the tracked reference ID is passed into WhatsApp.", notes: "For this live demonstration, I will open the WA-Ornis prompt in the OpenAI Platform, briefly show the business knowledge and chatbot instructions, enter a realistic customer question, and review the response and follow-up question. I will explain how the prompt was refined for accuracy and brand alignment. The WhatsApp Demo Hub can also be shown briefly to demonstrate how the tracked reference ID is passed into WhatsApp." },
  { eyebrow: "11 / Project milestone", title: "My Most\nExciting Moment", layout: "happiest", lead: "When the OpenAI chatbot finally responded the way I intended.", subtitle: "After repeated testing and refinement, the chatbot followed the intended tone, business knowledge and conversation flow.", notes: "My most exciting moment was when the OpenAI chatbot finally responded the way I intended. At the beginning, some responses were too general, too long or did not follow the intended conversation flow. I repeatedly tested the chatbot, adjusted the instructions and added clearer business knowledge, rules, restrictions and examples. Eventually, the chatbot followed the intended tone, business knowledge and conversation flow more consistently. This taught me that prompt engineering involves testing, observing weaknesses and refining instructions until the behaviour matches the business need." },
  { eyebrow: "12 / Biggest challenge", title: "My Biggest\nChallenge", layout: "challenge", lead: "How do I make AI flexible without making it uncontrolled?", subtitle: "A chatbot can generate an answer, but a business system needs the correct answer.", notes: "My biggest challenge was making the chatbot system reusable for different businesses without making the AI too general or uncontrolled. Every business needed separate information and restrictions. The tracked reference ID identifies the selected WhatsApp route, while the prompt must remain accurate and avoid unsupported promises. Human judgement is still required to verify the response and decide when support should take over." },
  { eyebrow: "13 / Solution", title: "Separate. Restrict.\nTrack. Test. Escalate.", layout: "checklist", items: ["Separate instructions for every business", "Use only confirmed brand knowledge", "Restrict unsupported promises", "Track the selected flow using a reference ID", "Test incomplete and repeated questions", "Escalate complex cases to a human"], notes: "I addressed the challenge by separating instructions for every business, using only confirmed brand knowledge, restricting unsupported promises, tracking the selected flow with a reference ID, testing incomplete and repeated questions, and escalating complex cases to a human." },
  { eyebrow: "14 / Reflection", title: "What makes me\ndifferent from AI?", layout: "closing", subtitle: "Reflection & Future", lead: "Learn how to configure, verify and connect AI—not only generate a reply.", cards: [{ title: "AI", body: "Generates replies quickly" }, { title: "ME", body: "Understands the business objective and writes better instructions" }, { title: "AI", body: "Follows instructions" }, { title: "ME", body: "Verifies responses, connects the correct flow and decides when human support is required" }], notes: "Before this internship, I viewed a chatbot mainly as a tool that answers questions. Now I understand that my value involved understanding the business objective, writing and refining instructions, verifying responses, connecting the correct business flow and deciding when human support was required. AI helped me work faster, but it could not replace human responsibility." },
  { eyebrow: "17 / Closing", title: "Thank You\n& Q&A", layout: "finalQna", lead: "Thank you for your attention.", subtitle: "I’m ready for your questions.", notes: "Before I end, I would like to thank LOCUS-T, Digital Bee, my supervisors, the team and my fellow interns for their guidance and support throughout my internship. This experience gave me the opportunity to explore AI beyond ChatGPT, test my own ideas and understand how chatbots, websites, dashboards and business workflows can work together. And after preparing all of these slides, I am also happy to say that the presentation is finally done. Thank you for your attention. I am now ready for your questions. The meme says to search in ChatGPT, but for now, you can ask me first." },
]

export const PRESENTER_NOTES = CHATBOT_SLIDES.map((slide, index) => ({ slide: index + 1, title: slide.title.replace("\n", " "), script: slide.notes }))
